import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Pokedex from '../components/Pokedex'
import QUERY_POKEMON_FETCH from '../config/queryPokemonFetch'

export default function FetchApi({pokemons}) {
  return  (
    <div className={styles.container}>
            <Head>
              <title>GraphQL Hooks</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
              <h1 className={styles.title}>
                Welcome to the World of Pokemon!
                FETCH API
              </h1>

              <Pokedex data={pokemons} />

            </main>
          </div>
  );
}

export const getServerSideProps = async () => {
  const API_URL = 'https://beta.pokeapi.co/graphql/v1beta';
  const fetchPokemons = async () => {
    const response = await fetch(API_URL, {
      method: 'POST',
      Accept: 'api_version=2',
      'Content-Type': 'application/graphql',
      body: JSON.stringify({ query: QUERY_POKEMON_FETCH })
    });
    const responseData = await response.json();
    return responseData.data
  }
  const pokemons = await fetchPokemons();

  return {
    props: {
      pokemons
    }
  }

}
