import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { GraphQLClient, ClientContext } from 'graphql-hooks';
import WithGraphQLHooks from '../components/WithGraphQLHooks';
import Link from 'next/link';

const client = new GraphQLClient({
  url: 'https://beta.pokeapi.co/graphql/v1beta',
});

export default function GraphQLHooks() {
  return (
    <ClientContext.Provider value={client}>
      <div className={styles.container}>
        <Head>
          <title>GraphQL Hooks</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Link href="/graphql-hooks-ssr">Go To GraphQl-Hooks-SSR</Link>
          <h1 className={styles.title}>Welcome to the World of Pokemon!</h1>
          <WithGraphQLHooks />
        </main>
      </div>
    </ClientContext.Provider>
  );
}
