import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the World of Pokemon!</h1>
        <div className={styles.wrapper}>

        <Link href="/fetch-api">Go To Fetch-API</Link>
        <Link href="/fetch-api-ssr">Go To Fetch-API-SSR</Link>
        <Link href="/graphql-hooks">Go To Grapql-Hooks</Link>
        <Link href="/graphql-hooks-ssr">Go To Grapql-Hooks-SSR</Link>
        <Link href="/urql">Go To Urql</Link>
        <Link href="/urql-ssr">Go To Urql-SSR</Link>
        </div>
      </main>
    </div>
  )
}
