import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { getClient, withClient } from '../config/urqlClient';
import QUERY_POKEMON from '../config/queryPokemon';
import { useQuery, Provider } from 'urql';
import Pokedex from '../components/Pokedex';
import Link from 'next/link';

const Urql = () => {
  const [res] = useQuery({ query: QUERY_POKEMON });
  return (

      <div className={styles.container}>
        <Head>
          <title>GraphQL Hooks</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.flexWrapper}>
            <Link href="/urql-ssr">Go to Urql</Link>
            <Link href="/urql-ssg">Go to Urql-SSG</Link>
            <Link href="/">Go Home</Link>
          </div>
          <h1 className={styles.title}>Welcome to the World of Pokemon!</h1>
          {res.fetching ? <p>Loading...</p> : <Pokedex data={res.data} />}
        </main>
      </div>

  );
};

export default withClient(Urql);
